# shiro config
shiro:
  appServer: http://192.168.1.12/${shiro.projectCode}-web
  casServer: http://192.168.1.13/cas
  securityServer: http://192.168.1.14/security-server/
# logback config
logging:
  # TRACE < DEBUG < INFO < WARN < ERROR
  log-level: DEBUG